pyms:
  services:
    metrics: true
    requests:
      propagate_headers: true
    
    tracer:
      client: "jaeger"
      host: "10.5.16.212"
      component_name: "ms14_mail"
    
  config:
    debug: true
    APP_NAME: "ms14_mail"
  

    