pyms:
  services:
    metrics: true
    requests:
      propagate_headers: true
    tracer:
      client: "jaeger"
      host: "10.5.16.212"
      component_name: "ms1_login"
  config:
    debug: true
    APP_NAME: "ms1_login" 
    